# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.20.1
yarn_mappings=1.20.1+build.10
loader_version=0.16.3

# Mod Properties
mod_version=1.0.1
maven_group=net.celsiusqc.create_wt
archives_base_name=create_wt
mod_loader=fabric  # Change to "neoforge" if using NeoForge

# Dependencies
fabric_version=0.92.2+1.20.1

# Create
# https://modrinth.com/mod/create-fabric/versions
create_version = 0.5.1-j-build.1631+mc1.20.1

# Ad Astra
# https://modrinth.com/mod/ad-astra/versions
ad_astra_version = 1.15.20

# Development QOL
# Create supports all 3 recipe viewers: JEI, REI, and EMI. This decides which is enabled at runtime.
# set to 'disabled' to have none of them.
recipe_viewer = jei
# JEI - https://www.curseforge.com/minecraft/mc-mods/jei/files/all
jei_version = 15.2.0.22
# REI - https://modrinth.com/mod/rei/versions
rei_version = 12.0.626
# EMI - https://modrinth.com/mod/emi/versions
emi_version = 1.1.18+1.20.1

# Mod Menu - https://modrinth.com/mod/modmenu/versions
modmenu_version = 7.1.0